name: NovaTerm CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ matrix.target }}

    - name: Cache Dependencies
      uses: swatinem/rust-cache@v2
      with:
        workspaces: "core gui plugins nova-term"

    - name: Build All Crates
      run: cargo build --release --all --target ${{ matrix.target }}

    - name: Run Tests
      run: cargo test --all --no-fail-fast

    - name: Code Coverage
      if: matrix.os == 'ubuntu-latest'
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: --all --out Lcov --output-dir ./target/coverage

    - name: Run Benchmarks
      run: cargo bench --no-run
        
    - name: Check Documentation
      run: |
        cargo doc --no-deps --document-private-items
        ! grep -R "// TODO" src/